### ISSUE TITLE
404 Error when deploying on vercel

### ISSUE THREAD

**Issue by PatelN123** [vercel/platforms#69]
Hi, 

I encounter the 404 error when I deploy this to vercel. 
Here is the repo: https://github.com/PatelN123/prod/tree/main/platforms

Thanks

**Comment by danieldev046** [comment]
@PatelN123 Did you find a solution for this?

**Comment by PatelN123** [comment]
> @PatelN123 Did you find a solution for this?

No, I didn't. :(

**Comment by soloamilkar** [comment]
Most likely this is a problem with your `_middleware` file, guys. I was having this same issue and editing the `_middleware` fixed it. Basically when getting the `currentHost` and when comparing **hostnames** against your **domains**. You need to be 100% that you setting this information correctly in relation with your domain settings in your vercel dashboard.

PD: I bought a xyz domain to test the app. I guess that helped too.

**Comment by drewes** [comment]
@soloamilkar would you mind elaborating a bit more? I can't seem to be able to resolve the issue. What did refer to with domain settings on the Vercel dashboard?

**Comment by steven-tey** [comment]
This is probably due to an incorrect configuration of your custom domain.

You can also use wildcard subdomains on .vercel.app links that are associated with your Vercel team slug.

In the case of the demo, our team slug is `platformize`, thus `*.platformize.vercel.app` works. Do note that you'll still need to add `*.platformize.vercel.app` as a wildcard domain on your Vercel dashboard.

I updated the comment [here](https://github.com/vercel/platforms/blob/main/pages/_middleware.ts#L25-L28) to make things clearer.

**Comment by avatarangg** [comment]
same problem with me

**Comment by eliagoris** [comment]
I had the same error.

_The solution is to NOT skip the domain configuration on [this guide](https://vercel.com/guides/nextjs-multi-tenant-application#4.-configure-rewrites-for-multi-tenancy)_

**To explain further, I'll write the steps that solved for me:**

1. Add your custom domain to your Vercel project domains settings:
  - Add both your base domain (`yourdomain.com`) and also wildcard domain (`*.yourdomain.com`)
  _As I have seen, .vercel.app domains don't work with wildcard, so you SHOULD  use a custom domain instead of .vercel.app_

2. Add your domain to the `middleware.ts` file:
  -  Add `.yourdomain.com` [to this line](https://vercel.com/guides/nextjs-multi-tenant-application#4.-configure-rewrites-for-multi-tenancy) (replace `.vercel.pub` with your domain)
  - Add `yourdomain.com` [to this line](https://github.com/vercel/platforms/blob/main/middleware.ts#L51) (replace `platformize.vercel.app` with your domain)

**Comment by steven-tey** [comment]
Hey ya'll, following up on this – @PatelN123 @danieldev046 @drewes @avatarangg can y'all share a bit more on the issue you're facing?

FYI I updated the comment [here](https://github.com/vercel/platforms/blob/main/middleware.ts#L41-L44) to make things clearer.

**Comment by Gaccoo** [comment]
I am having the same issues. I followed [this](https://vercel.com/guides/nextjs-multi-tenant-application) guide. Purchased a domain thinking that it will do some magic, but nothing works. When I go to my-domain.com it shows 404, when I go to app.my-domain.com it shows that deployment has not been found.
I have read through the guide like 100 times checking if I have missed something.

**Comment by Thebro57** [comment]
I’m having this same problem. I’m trying to test out Vercel and its GitHub capabilities by using https://github.com/Thebro57/Ultraviolet for a repository, since I don’t currently develop on GitHub. It keeps coming up as a 404, and I currently am broke (XD) and don’t want to spend money on a domain. Help, please?

**Comment by shahadadrohid** [comment]
I got cannot get / route error in express deploy. what can i do now?

**Comment by tutnyal** [comment]
> I had the same error.
> 
> _The solution is to NOT skip the domain configuration on [this guide](https://vercel.com/guides/nextjs-multi-tenant-application#4.-configure-rewrites-for-multi-tenancy)_
> 
> **To explain further, I'll write the steps that solved for me:**
> 
> 1. Add your custom domain to your Vercel project domains settings:
> 
> * Add both your base domain (`yourdomain.com`) and also wildcard domain (`*.yourdomain.com`)
>   _As I have seen, .vercel.app domains don't work with wildcard, so you SHOULD  use a custom domain instead of .vercel.app_
> 
> 2. Add your domain to the `middleware.ts` file:
> 
> * Add `.yourdomain.com` [to this line](https://vercel.com/guides/nextjs-multi-tenant-application#4.-configure-rewrites-for-multi-tenancy) (replace `.vercel.pub` with your domain)
> * Add `yourdomain.com` [to this line](https://github.com/vercel/platforms/blob/main/middleware.ts#L51) (replace `platformize.vercel.app` with your domain)

This was very helpful. Thanks!

also, for those still facing the issue, do the above. Here is how I fixed mine.

My hostname or NEXT_PUBLIC_ROOT_DOMAIN is "ainime.me"

1. In vercel, don't forget to change the NEXT_PUBLIC_ROOT_DOMAIN under settings/environment variables.
![image](https://github.com/vercel/platforms/assets/16125367/37cf87d4-2330-4ec1-a649-0c80fed75ce4)

2. and in your middleware.ts file, I made sure to add the "www" to your domain file, the Get hostname of request line will make your host name ".ainime.me" instead of "ainime.me". This will make the middleware think this is a URL in your app, but it doesn't exist so it returns a 404page not found. see what I did below.
` if (
    hostname === "www.ainime.me" || "ainime.me" ||
    hostname === process.env.NEXT_PUBLIC_ROOT_DOMAIN
  ) {
    return NextResponse.rewrite(
      new URL(`/home${path === "/" ? "" : path}`, req.url),
    );
  }`

3. With a "www." in front of your domain name, in vercel under your project domain settings, your need to have your domain without the  "www." in front forward to the one with it. See below
![image](https://github.com/vercel/platforms/assets/16125367/456f14d5-8da1-426f-894a-ef82b237283e)
