### ISSUE TITLE
How the On-demand ISR work for multiple subdomains?

### ISSUE THREAD

**Issue by futantan** [vercel/platforms#76]
I noticed a great feature On-demand ISR, but I'm not sure how to make it work for multiple subdomains.
I read the source code of this repo, but the usage is:
```
res.unstable_revalidate(urlPath);
```

What if two sites have the same urlPath? For example `alice.github.com/hello` and `bob.github.com/hello`

**Comment by jmotes** [comment]
@futantan I've been wondering the same. But, after looking at the source code I think it will work fine if you have your _middleware.ts file setup correctly.

https://github.com/vercel/next.js/blob/c947c9320619f1bd9a786bf7f3d1b36b79bde8b0/packages/next/server/api-utils/node.ts#L311

All unstable_revalidate is doing is making a request for the page with the `PRERENDER_REVALIDATE_HEADER` set, so if your middleware reroutes that request to _sites/[hostname]/[path], then it should delete the files at the path for the correct website, provided you use the correct site's domain when making the request to your /api/revalidate endpoint.

**Comment by futantan** [comment]
@jmotes Thanks for your help!

**Comment by peec** [comment]
Thanks for providing this information, i could not understand why only one site got cleared but it was because I only use one domain to clear cache, not multiple!

I only have one webhook to clear multiple sites, so what i did was  to modify the host based on what i get from the webhook request to the /api/cache-clear endpoint.

So i did something like this in my `/api/cache-clear` webhook.


```typescript

const clearCacheApiHandler = async (
  req: NextApiRequest,
  res: NextApiResponse
) => {
    const { forHost } = req.body;

    if (forHost && !req.headers.host?.startsWith("localhost")) {
      // MODIFY host header, so the middleware that receives the request can route correctly.
      console.log({ forHost }, "Found host domain to clear cache.");
      res.setHeader("host", forHost );
      req.headers.host = forHost ;
    }
    
    // Compute paths
    paths = []
  
    await Promise.all(
      paths.map(async (path) => {
        await res.unstable_revalidate(path);
      })
    );
}
export default clearCacheApiHandler;
```

**Comment by brikiernan** [comment]
@peec Can I ask you what you are using for the path? Would it be...

`
'/_sites/the-site-subdomain-or-custome-domain' // for the site homepage?
'/_sites/the-site-subdomain-or-custome-domain/post1' // for the site posts?
`

**Comment by peec** [comment]
> @peec Can I ask you what you are using for the path? Would it be...
> 
> `'/_sites/the-site-subdomain-or-custome-domain' // for the site homepage?` `'/_sites/the-site-subdomain-or-custome-domain/post1' // for the site posts?`

For the path i use relative paths related to the domain. So basically.

```
    paths = ["/news", "/news/my-new-page-is-ready", "/blog", "/blog/my-post"]
```

The core part is:

``` 
    if (forHost && !req.headers.host?.startsWith("localhost")) {
      // MODIFY host header, so the middleware that receives the request can route correctly.
      console.log({ forHost }, "Found host domain to clear cache.");
      res.setHeader("host", forHost );
      req.headers.host = forHost ;
    }
    
```

Because `unstable_revalidate` will then query the host with correct host, and revalidate only that specific domain `forHost`. 

The _middleware.js takes care of the /_sites/ part, just like in this github repo.
